<?php

namespace App\Ship\Exceptions\Handlers;

use Apiato\Core\Exceptions\Handlers\ExceptionsHandler as CoreExceptionsHandler;
use Apiato\Core\Traits\ApiResponseTrait;
use App\Ship\Parents\Controllers\Codes\GlobalStatusCode;
use Throwable;

/**
 * Class ExceptionsHandler
 *
 * A.K.A (app/Exceptions/Handler.php)
 *
 * @author  Mahmoud Zalt  <mahmoud@zalt.me>
 */
class ExceptionsHandler extends CoreExceptionsHandler
{
    use ApiResponseTrait;

    public function render($request, Throwable $e)
    {
        if(env('APP_DEBUG') === true){
            return parent::render($request, $e); // TODO: Change the autogenerated stub
        }

        if(method_exists($e, 'getStatusCode')) {
            if($e->getStatusCode() === GlobalStatusCode::AUTHENTICATION_FAIL) {
                return $this->errorResponse($request, '', [], GlobalStatusCode::AUTHENTICATION_FAIL);
            } elseif ($e->getStatusCode() === GlobalStatusCode::AUTHENTICATION_TIMEOUT_FAIL) {
                return $this->errorResponse($request, '', [], GlobalStatusCode::AUTHENTICATION_TIMEOUT_FAIL);
            } elseif ($e->getStatusCode() === GlobalStatusCode::RESOURCE_NOTHING) {
                return $this->errorResponse($request, '', [], GlobalStatusCode::RESOURCE_NOTHING);
            }
        }
        if(isset(GlobalStatusCode::$status_texts[$e->getMessage()])) {
            return $this->errorResponse($request, '', [], $e->getMessage());
        }
        elog('最终捕获获取异常', $e);
        return $this->errorResponse($request, '', [], GlobalStatusCode::RESULT_SYSTEM_FAIL_CODE);

    }

}
